export const OKAY_STATUS_CODE = 200
export const BAD_REQUEST_STATUS_CODE = 400
export const NOT_FOUND_STATUS_CODE = 404
export const SERVER_ERROR_STATUS_CODE = 500
export const MONGODB_DUPLICATE_CODE = 11000
